### PR TITLE
Ticked build number, rerendered with 2.2.1, update template

### PR DESCRIPTION
**Pull request by pmlandwehr**

### CODE REVIEW

**Comment by pmlandwehr** [comment]
(ping @conda-forge/pyyaml on getting this pull request accepted)

**Comment by pmlandwehr** [comment]
This no longer seems necessary, so closing.

**Comment by jakirkham** [comment]
Sorry for the delay @pmlandwehr. This is a welcome change. Would need a build number bump to get new packages with the license file. Otherwise would be happy to merge it.

**Comment by pmlandwehr** [comment]
This is ready for merge.

**Comment by jakirkham** [comment]
Thanks @pmlandwehr.

**Pull request merged**
