### PR TITLE
Remove SETUPTOOLS_USE_DISTUTILS = local for py38.

### PR DESCRIPTION
**Pull request by erykoff**
This option does not properly pass through compiler flags until python 3.9.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes https://github.com/conda-forge/pyyaml-feedstock/issues/38

### CODE REVIEW

**Comment by erykoff** [comment]
Looking at the py38 build https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/402090/logs/110 it seems as though #38 is fixed, e.g.:
```
2021-11-03T04:41:01.2842270Z creating build/temp.macosx-11.0-arm64-3.8
2021-11-03T04:41:01.2843240Z creating build/temp.macosx-11.0-arm64-3.8/yaml
2021-11-03T04:41:01.2846090Z arm64-apple-darwin20.0.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/pyyaml-6.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=11.0 -I$PREFIX/include -I$PREFIX/include/python3.8 -c yaml/_yaml.c -o build/temp.macosx-11.0-arm64-3.8/yaml/_yaml.o
```
and no warnings about ignoring files that have the wrong architecture.

**Comment by erykoff** [comment]
@conda-forge/pyyaml I believe this is good to go.

**Comment by jakirkham** [comment]
Thanks @erykoff! 😄

Do we need this for Python 3.7 as well? Also how does this affect non-macOS ARM builds?

**Comment by erykoff** [comment]
You are absolutely right about 3.7, I thought that was being dropped but apparently was confused.  The way this affects non-macOS ARM builds is that without this fix the builds will be done with some arbitrary default list of compiler flags and optimizations, and not with the conda-forge standardized flags that come from the compiler packages.

**Comment by jakirkham** [comment]
Thanks for checking 🙂

Yeah probably at some point we will drop 3.7. That hasn't happened yet. We've only dropped 3.6. Likely whenever 3.11 comes around (unless there is some reason to do that sooner).

Ok yeah in that case agree we want to use this patch on other architectures. Strange that they don't check whether the environment variable has been set externally before overriding (though have seen a few `Makefile`s with similarly bad behavior).

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks again! 😄

**Pull request merged**
